### ISSUE TITLE
Up-Grade you Plug-In

### ISSUE THREAD

**Issue by Andokan** [mhwlng/streamdeck-starcitizen#1]
Hi,
I use your plugin and it is great! During some customization of my stream deck I thought it will be better, if you can customize the plugin with a custimized xml file from Star Citizen.

I mean go into Starcitizen, create your own layout on keyboard, export this file, got your plugin read this file and set up a new selection menue inside the stream deck software.

Do you think this this will be possible?

best regards
Andokan

**Comment by mhwlng** [comment]
No that is not possible, sorry
