### ISSUE TITLE
Stream Deck + dial support?

### ISSUE THREAD

**Issue by Tuumke** [mhwlng/streamdeck-starcitizen#12]
Is it possible to add support for the stream deck + dial buttons?
I'd like to bind the laser to one of my dials. If i can give any files/support whatever, feel free to reach out as i can understand you might not have access to a stream deck + right away

**Comment by mhwlng** [comment]
Elgato does not prove an sdk for the dials. So this is not possible
Also the game does not provide status information like laser level

**Comment by Tuumke** [comment]
> Elgato does not prove an sdk for the dials. So this is not possible Also the game does not provide status information like laser level

Damn. That sucks. I tried assigning the mousewheel to a dial, but they don't support that (yet) either. Again, as in my other request, it's not about receiving laser levels from the game, just to operate it.

**Comment by mhwlng** [comment]
This plugin can't emulate a mousewheel 
So if you can't switch to up/down keyboard buttons in the game settings then it's not possible
