### ISSUE TITLE
Request: Use dual icons like System -> Hotkey Switch

### ISSUE THREAD

**Issue by Tuumke** [mhwlng/streamdeck-starcitizen#13]
Is it possible to set dual-icons on a static button? Or have a seperate "input" called Static Switch?
That functions like the hotkey switch with has 2 icons available? 1 for pushed down, 1 when it's not? 

Examples i could think of are:
Landing gear = up, icon = green. Landing gear = down, icon = red
Cruise control = on, icon = green. Cruise control = off, icon = red.

**Comment by mhwlng** [comment]
The game does not provide feedback on the status. So this is not possible

**Comment by Tuumke** [comment]
> 

It's not so for having status feedback, but it's for when it's pressed or not pressed. So if you press the button it takes the color. So basicly the request is to have the option to assign 2 icons, like on the System -> Hotkey Switch

**Comment by mhwlng** [comment]
No
I will not make landing gear up/ down image until he game tells me if the gear is currently up or down
See GitHub description where is described how to use multi action switch to set up toggle function with 2 images
