### ISSUE TITLE
Similar support for Loupedeck?

### ISSUE THREAD

**Issue by Limeqvist** [mhwlng/streamdeck-starcitizen#15]
Hi! 

I hope you don't mind me opening an issue here, I was wondering if you would be interested in looking into something similar for our control surfaces over at Loupedeck. We have similar consoles as what elgato provides and our SDK is in C#. You can email me at emil.lindqvist@loupedeck.com if you want to talk further :)

Regs,
Emil

**Comment by mhwlng** [comment]
I already own a loupedeck live, but I did not find a way to set up the button configuration to something like this :

![image](https://user-images.githubusercontent.com/1388886/211398635-139930e0-220d-4019-bf98-6d4e292e91c9.png)

![image](https://user-images.githubusercontent.com/1388886/211399029-920e2a3d-8ebe-47c0-ad2f-05ea463c285c.png)

I did not find a way in the loupedeck SDK to use the MakeProfileAction to set up dialog boxes like above examples with multiple separate dropdowns and edit boxes

**Comment by Limeqvist** [comment]
Hey,

Nice to hear nice to hear that you have a device, we actually will be including more action settings into the SDK shortly. If you are interested we can provide you with a beta hopefully sometime next week.

Regards,
Emil
***@***.***
EMIL LINDQVIST
Technical Sales Manager
Product Owner

LOUPEDECK OY
Museokatu 8
00100 Helsinki, Finland
www.loupedeck.com<https://loupedeck.com/>

**Comment by mhwlng** [comment]
Hi Emil
>> If you are interested we can provide you with a beta hopefully sometime next week.

I'm currently working on other projects that take up all my time. 

I'll check the new loupedeck SDK functionality again, after it's out of beta.
