### ISSUE TITLE
Plugin does not find Star Citizen install location if it is not on the C or D drive

### ISSUE THREAD

**Issue by dopeghoti** [mhwlng/streamdeck-starcitizen#16]
I have Star Citizen installed on the E drive on my system (as it's the most performant SSD), but your plugin failed to properly detect the install location from which to read the keybinds, and as such was not sending inputs to the game.  I had to manually add my path to the Plugin configuration file as described in the `README.md` file, at which point the plugin began to operate normally.

I suggest, if possible, having your plugin poll the system for present drives, and check for `Program Files/Star Citizen` on each drive rather than what it seems to do, which is only check the C and D drives.

**Comment by mhwlng** [comment]
Set game directory in appsettings.config
See readme for more details

**Comment by dopeghoti** [comment]
I have done so manually as I stated; the suggestion was to obviate the requirement to do so.

**Comment by mhwlng** [comment]
There are no plans to change the current system
