### ISSUE TITLE
Broken with recent StreamDeck update?

### ISSUE THREAD

**Issue by Vaygrim** [mhwlng/streamdeck-starcitizen#17]
I've recently updated to Stream Deck software version 6.5.0 (19904) and something about your Star Citizen plugin has stopped working. The button's don't even generate errors, that would at least be helpful.
I've tried reinstalling the plugin, recreating some of the buttons, even running the Stream Deck software with and without Admin Privileges. Nothing seems to fix it.

Any possibility you could get it up and running, perhaps?

THANKS!

**Comment by mhwlng** [comment]
I tested it with 6.5.0 (19904) and it works ok for me. 

I'm afraid that I cannot reproduce your problem.

If I try a button that is bound to the game's STAR MAP button (F2) then I see this in the log files when I toggle it:

2023-12-27 07:05:17.3241|INFO|com.mhwlng.starcitizen|44|{DikF2}
2023-12-27 07:05:19.7561|INFO|com.mhwlng.starcitizen|45|{DikF2}

**Comment by Vaygrim** [comment]
Bizarre, okay this means I need to do more testing and figure out what's happening.

The standard Stream Deck "HOTKEY" function works fine, but your specific ones don't. Hmmm.
