### ISSUE TITLE
Idea Salvage Hotkey ?

### ISSUE THREAD

**Issue by MrBretze** [mhwlng/streamdeck-starcitizen#18]
Hello, I can't found the Salvage function 👀

**Comment by mhwlng** [comment]
I see a lot of salvage buttons:
![image](https://github.com/mhwlng/streamdeck-starcitizen/assets/1388886/4bb9a47b-986b-4ced-94d8-21dfca7f7908)

![image](https://github.com/mhwlng/streamdeck-starcitizen/assets/1388886/d8c372b5-41c8-47d7-b9ad-4d746a4378dc)

**Comment by MrBretze** [comment]
I don't have this option in my setup

**Comment by MrBretze** [comment]
Oh i found the bug... The plugin don't find the location of my game...

**Comment by mhwlng** [comment]
The plug-in automatically shows ALL options with a keyboard binding. Are you using the latest game version? Maybe the button does not have a keyboard binding in your system? Or maybe the plug-in is looking in the wrong directory for the game files. Please check plug-in log file

**Comment by mhwlng** [comment]
You can configure directory of game in the plugin. Please check documentation how to do this

**Comment by MrBretze** [comment]
Its work, not "easy" but its works :D
Thanks you :)
