### ISSUE TITLE
problème assignation de touche

### ISSUE THREAD

**Issue by Tipapps** [mhwlng/streamdeck-starcitizen#20]
Bonjour, 

merci pour ce merveilleux plugins qui fonctionnait à merveille jusque ici.
Mais depuis que j'ai réinstaller SC sur un nouveau disque dur le plugins ne fonctionne plus. 
un voyant jaune apparait lorsque j'appui sur les touche du plugin sur mon streamdeck.
j'ai l'impression  que le chemin d'accès au touches n'est pas trouvé.
J'ai pourtant suivis les instruction et rentré manuellement le bon chemin d'accès... :/ pouvez-vous m'aider je suis a bout de solution.
Cordialement merci.

**Comment by mhwlng** [comment]
English please I don't speak French
Please check plugin log file for any errors and set directory of the game files manually in config file

**Comment by Tipapps** [comment]
![Capture d'écran 2024-04-15 144449](https://github.com/mhwlng/streamdeck-starcitizen/assets/166953076/116d2523-e75d-49d1-9a5a-3982154ee5a1)
Hello, thank you for your feedback.

I have already set directory of the game files manually in config file.
<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
  <add key="SCData_p4k" value ="E:\RSI\StarCitizen\LIVE\Data.p4k" />
  <add key="SCClientProfilePath" value ="E:\RSI\StarCitizen\LIVE\USER\Client\0\Profiles\default" />
</appSettings>

When i check plugin log :
(I only took the last 3 lines)
2024-04-15 14:39:49.7161|DEBUG|com.mhwlng.starcitizen|1|Logger Initialized
2024-04-15 14:39:49.7451|INFO|com.mhwlng.starcitizen|1|Init Star Citizen
2024-04-15 14:39:49.7531|INFO|com.mhwlng.starcitizen|1|E:\RSI\StarCitizen\LIVE\Data.p4k


Sincerely
thx.

**Comment by mhwlng** [comment]
please post the complete log file here
please post the actionmaps.xml here

**Comment by Tipapps** [comment]
![action](https://github.com/mhwlng/streamdeck-starcitizen/assets/166953076/2c109077-6756-42cf-9dd3-7b440895b807)
![log file](https://github.com/mhwlng/streamdeck-starcitizen/assets/166953076/a5bb0e1c-55f3-4e8e-803f-66a8cdaec968)

**Comment by mhwlng** [comment]
please post the files, not screenshots

**Comment by Tipapps** [comment]
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/14980075/pluginlog.log)

**Comment by Tipapps** [comment]
[actionmaps.xml.txt](https://github.com/mhwlng/streamdeck-starcitizen/files/14980191/actionmaps.xml.txt)

the format xml isn't support here so I transformed the file into ".txt". is ok for you ?

**Comment by mhwlng** [comment]
I still can't reproduce the problem.
can you please zip the whole plugin directory and post it here

**also try to start streamdeck.exe as administrator**

it seems that the plugin cannot read the pk4 file  and crashes immediately ?

Your log 


Init Star Citizen
E:\RSI\StarCitizen\LIVE\Data.p4k

my log

Init Star Citizen
C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k needs update : False
C:\Program Files\Roberts Space Industries\StarCitizen\LIVE\USER\Client\0\Profiles\default\actionmaps.xml
Keyboard Detected, language : 409 keyboard : 409 culture : en-US
Keyboard Detected, language : 409 keyboard : 409 culture : en-US
Keyboard Detected, language : 409 keyboard : 409 culture : en-US
monitoring key binding file
Finished Init Star Citizen

**Comment by Tipapps** [comment]
[com.mhwlng.starcitizen.sdPlugin.zip](https://github.com/mhwlng/streamdeck-starcitizen/files/14981572/com.mhwlng.starcitizen.sdPlugin.zip)

**Comment by mhwlng** [comment]
Your plugin files are the same as mine.

the plugin tries to read the pk4 file and crashes
compare mine to yours:
all missing extra files on yours are created automatically and this doesn't happen on your system.
![image](https://github.com/mhwlng/streamdeck-starcitizen/assets/1388886/03054e59-2e34-4116-ae39-bf75be57aa5b)

please try to start streamdeck.exe as administrator

if that doesn't help then I have no idea what the problem is on your pc?

**Comment by Tipapps** [comment]
I just tried to run it as administrator and the result is the same.
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/14981894/pluginlog.log)

the problem has persisted since the installation of RSI launcher 2.0.
could there be a link?

**Comment by mhwlng** [comment]
today I also installed the launcher 2.0 and all is ok for me

the pk4 is todays date (when I installed launcher 2.0):

![image](https://github.com/mhwlng/streamdeck-starcitizen/assets/1388886/066f75ef-84a2-4924-93d1-bd96232d7ccf)

I'm sorry, but I don't know what else to suggest...

**Comment by Tipapps** [comment]
ok thank you for your time I am also short of solutions :(
I completely rebooted my pc for nothing lol 
kind regards

**Comment by Sandrom06** [comment]
I had the problem from the moment I installed the new luncher and completely reinstalled the games. I didn't have the problem with the new luncher in beta without having to reinstall all the games.

**Comment by mhwlng** [comment]
I delete the game and re-installed it and now I see the same problem with the p4k file.
I see that the P4k is now a smaller size than before. (from 102GB to 96.7GB)
I have to investigate further if I can read the new file format.
This is will take a while. I am not sure if I will be able to. 
I will try to find some time this weekend.

**Comment by Sandrom06** [comment]
well I did a test, I reinstalled the old luncher and then I reinstalled the game and the plugin works. I then reinstalled the new luncher without reinstalling all the games and the plugin still works. the problem comes from the installation from the new luncher.

**Comment by mhwlng** [comment]
the new plugin version 1.1.2 should be able to read the new p4k format generated by the 2.0 launcher

**Comment by Tipapps** [comment]
oh perfect man!!! I'm going to test this right away. thank you very much for your feedback.
