### ISSUE TITLE
Function keys [static button] not registering

### ISSUE THREAD

**Issue by YSLBoatBoy** [mhwlng/streamdeck-starcitizen#21]
The function keys for my setup aren't working, but if I was to use just a hotkey instead of a function key it works. Not sure where the issue lies. I changed the app settings to point to my needed places: 
<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
  <add key="SCData_p4k" value ="H:\StarCitizen\StarCitizen\LIVE\Data.p4k" />
  <add key="SCClientProfilePath" value ="H:\StarCitizen\StarCitizen\LIVE\USER\Client\0\Profiles\default" />
</appSettings>

Below are both my logs and action maps. I've tried running as admin and everything, just seems like the Function pieces in the streamdeck themselves arent registering with SC. I've checked and made sure the hotkeys line up as well.

[actionmaps.xml.txt](https://github.com/mhwlng/streamdeck-starcitizen/files/15047339/actionmaps.xml.txt)
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/15047340/pluginlog.log)

**Comment by YSLBoatBoy** [comment]
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/15047388/pluginlog.log)
Here's probably a more telling log file

**Comment by mhwlng** [comment]
It's the same problem as the other open ticket:
https://github.com/mhwlng/streamdeck-starcitizen/issues/20

it looks like the plugin will have to be  completely rewritten, to be able to handle the changed p4k file format. I'm investigating.

Using the old launcher to install the game works ok.
Installing the new launcher without re-installing the game works ok.

**Comment by YSLBoatBoy** [comment]
Okay, thanks for the update on that. Let me reinstall the game with the old launcher, and then give it a try. thanks for the reply

**Comment by mhwlng** [comment]
the new plugin version 1.1.2 should be able to read the new p4k format generated by the 2.0 launcher

**Comment by YSLBoatBoy** [comment]
This fixed it, thanks so much for the update!
