### ISSUE TITLE
This doesn't pull the keybinds from the latest patch

### ISSUE THREAD

**Issue by Lungshot** [mhwlng/streamdeck-starcitizen#23]
As described in the title - love this plugin. Any help would be appreciated. It looks like it just pulls a default set of keybinds and not the ones star citizen is currently using.

**Comment by mhwlng** [comment]
use plugin version 1.1.2
use latest SC launcher 2.0.0.0
look on github for more instructions.
check the pluginlog.log file.
adjust the file path in appsettings.config. if that is the problem
