### ISSUE TITLE
Expand spindle/change (k)onfiguration

### ISSUE THREAD

**Issue by MarcusWolschon** [mhwlng/streamdeck-starcitizen#24]
The action "expand/contract spindle" on K (for US-English keyboards) is missing.

**Comment by mhwlng** [comment]
I don't find an option 'expand/contract spindle' in my (english) game 3.23.1-live.9204897 in options\keybindings

I see : flight - movement \ Cycle Configuration left-Alt K in the streamdeck.

**Comment by MarcusWolschon** [comment]
Yes, that's it.
Quite important for the Hull series of freighters. :)

**Comment by mhwlng** [comment]
I see it :
![image](https://github.com/user-attachments/assets/e9c9b459-6b1d-4c51-8841-3304764e8108)


If you don't see it in the dropdown :

use plugin version 1.1.2
use latest SC launcher 2.0.0.0
look on github for more instructions.
check the pluginlog.log file for any errors.
adjust the file path in appsettings.config. if that is the problem
