### ISSUE TITLE
Feature request:  Add support for multiple environments (e. g. LIVE, PTU, EPTU, etc.)

### ISSUE THREAD

**Issue by dopeghoti** [mhwlng/streamdeck-starcitizen#26]
This might be a not-insignificant amount of work I suppose, so I can understand why you might want _not_ to, but it might be worth considering supporting multiple installs, as the last few patches to the game have added new bindings that differ from those in the `LIVE` build; this might facilitate being able to still use the plugin when switching between builds in the event that some keys overlap between the configurations.

**Comment by mhwlng** [comment]
no sorry, I have no plans to do this.  what you see is what you get... I'll do bugfixes, and make sure it works with new SC versions, but that's it

**Comment by dopeghoti** [comment]
I understand.  Thanks for the response.
