### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by GameAreaCZ** [mhwlng/streamdeck-starcitizen#28]
When I click nothing is happening

**Comment by GameAreaCZ** [comment]
Fixed by manual edit the file paths.

**Comment by ghost** [comment]
Sorry to re-open this one, but I want to ask which paths you fixed. This just started happening to me today. My main profile no longer works but it works when I press the button in the main profile to navigate to a different profile. So, only the buttons in the main profile do nothing in Star Citizen. So, maybe I need to look at file paths.

**Comment by ghost** [comment]
Well, my trouble started when I renamed LIVE to HOTFIX and verified files (this is a shortcut to install all of a new environment in Star Citizen). When I named HOTFIX back to LIVE and verified files, my default page for Star Citizen works again. I don't know if this is the real explanation or something else happened.
