### ISSUE TITLE
Just one question!

### ISSUE THREAD

**Issue by Costinh4** [mhwlng/streamdeck-starcitizen#29]
This is not a mistake! It's just a few questions, I have the Rise Mode Streaming Vision 01, an alternative version of the stream deck. Would it be possible for me to somehow install the star citzen plugin on this device?

link for my device.**https://risemode.com/mesacontroladora/**

**Comment by Costinh4** [comment]
If it can be done, but it is a lot of work, we can see a value for the service.

**Comment by mhwlng** [comment]
no sorry, this is impossible.
this plugin only works with the elgato/corsair streamdeck software.

**Comment by Costinh4** [comment]
tks for support
