### ISSUE TITLE
Seperate Key Down and Key Up

### ISSUE THREAD

**Issue by garv3** [mhwlng/streamdeck-starcitizen#3]
First of all thanks for this plugin. It's pretty awesome.
One thing that would be very useful would be seperate buttons for key down and key up events.
This could be used in multi actions using a delay. Then one could for example for 'exit seat' add a key down event, a delay and a key up event. This way the player could simply press the button instead of holding it down. Additionally this could be combined with other actions like switching to a on-foot profile after leaving a seat.
As an alternative a button that allows to set a delay would be great.

Thanks!

**Comment by mhwlng** [comment]
I'll consider that for a future update. 
I don't want to make the dropdown three times the size (normal, up, down) 
So, the button  template would have to be redesigned with 3 extra radio buttons. (normal, up, down)

**Comment by garv3** [comment]
Or a seperate button with one more option: down time in ms

**Comment by mhwlng** [comment]
@garv3 

I tested the current static button type with the multi-action button 
and it works fine for me.

the streamdeck software takes care of the key down/up events, for each step in the multi-action list.

Do you have a use case, where it is not working for you ?

**Comment by mhwlng** [comment]
@garv3 

see version 1.,0.7
