### ISSUE TITLE
3.24.2 not wokring 

### ISSUE THREAD

**Issue by CandecYr** [mhwlng/streamdeck-starcitizen#30]
hello,
i have a problem with the streamdeck plugin that does not respond at all in the game
i am in 3.24.2 with the latest launcher 2.0.6
i have already deleted and reinstalled the plugin that did not find the path to my starcitizen
now it normally finds the path and does not display an error in the log but no action is seen in the game
i want to use the plugin for managing the camera in F4 and whether by holding F4 on the keyboard or on a streamdeck key F4 the camera movement actions do not work. same for a W key for the freelook which does not need F4 pressed.

by the way do you think it would be possible to put a double action to have the F4 + a key in order to have only one key to press to move the camera?

i put you the appsettings.config config file

<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
  <add key="SCData_p4k" value ="D:\SteamLibrary\steamapps\common\StarCitizen\LIVE\Data.p4k" />
  <add key="SCClientProfilePath" value ="D:\SteamLibrary\steamapps\common\StarCitizen\LIVE\USER\Client\0\Profiles\default" />
</appSettings>

and the pluginlog.log log file

[pluginlog.log](https://github.com/user-attachments/files/17574596/pluginlog.log)

thanks in advance

**Comment by mhwlng** [comment]
This plug-in only works with holding Ctrl/shift/alt keys as modifiers.
Holding f4 or any other key does not work. You can’t use this plug-in for that.

**Comment by CandecYr** [comment]
hello,

very sorry to read that :(

too bad I have to look if there is not another solution so thanks anyway

**Comment by CandecYr** [comment]
hi,

just to say that after more research I found my problem, I did not run the streamdeck software as an administrator so it did not send the information to the game.

once in admin it works and even with the F4 key pressed on the keyboard, and also with an F4 key from the plugin on the streamdeck + a second key pressed on the streamdeck (2 finger).

so everything is good :D
