### ISSUE TITLE
Keybinding 4.0

### ISSUE THREAD

**Issue by Beuzzette** [mhwlng/streamdeck-starcitizen#33]
Hi ! 
If you can update the list of keybinding with 4.0 feature it will be appreciate !
Thanks for you're works ! Good job

**Comment by mhwlng** [comment]
The software does not need to be updated.
The 4.0 files are in a different directory
You need to set that up in :
%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.starcitizen.sdPlugin\appsettings.config
(See instructions on main github page)
