### ISSUE TITLE
Feature Request: Hold Button

### ISSUE THREAD

**Issue by ZOXSOCKS** [mhwlng/streamdeck-starcitizen#4]
The game allows certain actions to be done differently when the hotkey is held. For example, firing countermeasures can be done in two ways: you can fire a single flare by tapping the countermeasures button, or you can "queue up" multiple of the flares by holding the button, then releasing.

Allowing the streamdeck buttons to be held to fire multiple chaff, or any other function that can be used by holding the key down, would be a super useful addition!

Thanks

**Comment by mhwlng** [comment]
This is already the case.
 The key-up event is only sent when you release the stream deck button.

**Comment by mhwlng** [comment]
@ZOXSOCKS 

see version 1.0.7

in case that doesn't do what you need, there is now a new button type, where you can define the time between key down and key up events (see readme.md for more info)
