### ISSUE TITLE
Error parsing certain bindings

### ISSUE THREAD

**Issue by GrimGadget** [mhwlng/streamdeck-starcitizen#5]
I ran across a bug today with a specific binding.  The binding info seems to not be parsed correctly.

In SC:
![image](https://user-images.githubusercontent.com/30664204/164867170-c33e72e3-19ac-4c62-bba7-1d3a291f693d.png)

In the exported controls XML:
![image](https://user-images.githubusercontent.com/30664204/164867284-7a3aeb8f-3d47-4260-be9e-e76db5a15829.png)

In the keybindings.csv file in the plugin folder:
![image](https://user-images.githubusercontent.com/30664204/164867461-2715eec9-09e2-4bc8-9e44-a538d3468936.png)

How it appears in the Stream Deck UI when I attempt to set a button for Cooler Down:
![image](https://user-images.githubusercontent.com/30664204/164867668-1828fe61-bdc6-4db5-ae8e-3b2169d9037f.png)

I went ahead and set it, because I wasn't sure if it was an error parsing the inputs, or if it was just a visual glitch while setting the button functionality.  The button does, indeed, send RAlt+Escape to the game window.

**Comment by mhwlng** [comment]
problem with page down key is fixed in 1.0.8
