### ISSUE TITLE
Doesn't see keybinds after latest patch 3.17.1

### ISSUE THREAD

**Issue by Degrager** [mhwlng/streamdeck-starcitizen#6]
It stopped working and it doesn't see any of the keybinds

**Comment by mhwlng** [comment]
I'm testing with 3.17.1 live and it works fine for me.
please check the plugin log file for errors
are you sure that your keyboard bindings haven't changed in-game?

**Comment by Degrager** [comment]
nevermind I didn't realize I had to update my game path :\
