### ISSUE TITLE
Star Citizen not picking up keybinds from Streamdeck

### ISSUE THREAD

**Issue by Grootloops33** [mhwlng/streamdeck-starcitizen#7]
Hey! I can't get any buttons to work in-game.

I've updated my paths, restarted Stream Deck, and restarted Star Citizen. Can't get it to work.
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/8970857/pluginlog.log)
[appsettings - Copy.txt](https://github.com/mhwlng/streamdeck-starcitizen/files/8970859/appsettings.-.Copy.txt) (I had to convert this to a .txt because github doesnt allow uploading .config files.

**Comment by mhwlng** [comment]
```
if (Directory.Exists(scp)) return scp; // EXIT Success
issue = string.Format("SCClientPath - StarCitizen\\LIVE or PTU subfolder does not exist: {0}", scp);
```

log: StarCitizen\LIVE or PTU subfolder does not exist: E:\StarCitizen\LIVE

so the plugin can't find E:\StarCitizen\LIVE OR it has no access rights to it?
try starting streamdeck.exe as administrator or modify permissions

**Comment by Grootloops33** [comment]
The problem is that Star Citizen is not installed there. Hence why I set the correct path in Appsettings. It has never been installed there, and the folder doesn't even exist.

**Comment by mhwlng** [comment]
there is something wrong in your appsettings file, there is a strange character ?

![image](https://user-images.githubusercontent.com/1388886/175576322-d4c6cd7a-76e1-4ba1-9676-71849d60fc9d.png)

**Comment by Grootloops33** [comment]
There shouldn't be. It could be due to me having to convert it to .txt and you having to convert it back. The pluginlog does appear to be logging that it's finding the actionmaps.xml

Edit: I copied the dir from the file's details section.

**Comment by mhwlng** [comment]
I don't think so

I think the file is wrong.

the code checks if the pk4 file exist and it doesn't do anything if it can't find the file :
  if ((!string.IsNullOrEmpty(appSection["SCData_p4k"]) && File.Exists(appSection["SCData_p4k"])))
                    {
                        return appSection["SCData_p4k"];
                    }

**Comment by Grootloops33** [comment]
[pluginlog.log](https://github.com/mhwlng/streamdeck-starcitizen/files/8978459/pluginlog.log)
I rewrote the path to the file now and It works.. Odd. Thanks for the assist!
