### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by KraKeYn** [mhwlng/streamdeck-starcitizen#9]
Hi
I started modifying your plugin to add a toggle bouton but I cant compil the program.
I ve got stuck with ": error NU1201: Le projet WindowsInput n'est pas compatible avec net40 (.NETFramework,Version=v4.0). Le projet WindowsInput prend en charge : net48 (.NETFramework,Version=v4.8) [E:\0_All\Document\streamdeck-starcitizen-master\starcitizen.sln]"
(sorry it s in french) 
And I wonder if you can help me overhide it or compil the program for me
Thanks
[streamdeck-starcitizen-master.zip](https://github.com/mhwlng/streamdeck-starcitizen/files/9596501/streamdeck-starcitizen-master.zip)

**Comment by mhwlng** [comment]
sorry, I have no idea

just to be sure 
I just downloaded the source code from github to a new pc with windows 11, visual studio 2022 and dotnet 4.8 installed
and it compiles without errors. if you only have dotnet 4.0 installed, then it won't work...

**Comment by KraKeYn** [comment]
> sorry, I have no idea
> 
> just to be sure I just downloaded the source code from github to a new pc with windows 11, visual studio 2022 and dotnet 4.8 installed and it compiles without errors. if you only have dotnet 4.0 installed, then it won't work...

I only have dotnet 4.8 and 4.6 but i cannot solve this error, I know it’s not your job or anything’s but could you please compile the program so I could use it ?

**Comment by mhwlng** [comment]
no sorry. I do not give that kind of support.

**Comment by mhwlng** [comment]
p.s. 

the released file is a zip file :

https://github.com/mhwlng/streamdeck-elite/releases/download/v2.4.2/com.mhwlng.elite.streamDeckPlugin

you could change the extension to .zip and extract the compiled dll from it and change the solution, to use it directly.
(I don't give support on how to do that)

**Comment by KraKeYn** [comment]
Thx but my probleme is with the compilation my pc seem to have a dotnet 4.0 but i can’t see it in my drive, even when I do a dotnet —version I only 4.8 ( after4.6 undowload and reboot)

**Comment by mhwlng** [comment]
I have no idea.. sorry
